### PR TITLE
jsdoc for the main class

### PR DESCRIPTION
**Pull request by sohank1**

### CODE REVIEW

**Comment by sohank1** [comment]
1 sec not done

**Comment by sohank1** [comment]
this is ready

**Comment by seasaltsaige** [comment]
MERGE CONFLICTS FRIK U

**Comment by sohank1** [comment]
BRUH

**Comment by sohank1** [comment]
ight fixed

**Review by seasaltsaige — APPROVED** [review]
sdabjidshjagiukdsaguidsa

**Comment by sohank1** [comment]
> sdabjidshjagiukdsaguidsa

wow thats insane

**Pull request merged**
