### PR TITLE
sendPresence() method

### LINKED ISSUE #2: Singular Methods For Sending Data
### Remember to create the branches.
| Branch | Description |
| ----------- | ----------- |
| total-guilds-method| A method to just send the guilds|
| total-members-method  | A method to just send the members|
| presence-method  |A method to just send the presence|
### When u add the jsdoc. Add it in the jsdoc branch.
# What we have done
- [x] **total-guilds-method** (@aspectiscool)
- [x] **total-members-method** (@CreeperPlanet26)
- [x] **presence-method** (@CreeperPlanet26)

### PR DESCRIPTION
**Pull request by sohank1**

### CODE REVIEW

**Comment by sohank1** [comment]
ill add jsdoc after this gets merged

**Comment by sohank1** [comment]
Still need to add jsdoc to this

**Comment by sohank1** [comment]
ight finished

**Comment by sohank1** [comment]
please review

**Review by seasaltsaige — APPROVED** [review]
hey, thats pretty good

**Pull request merged**
